name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id AKIAXYKJRLVUEAI544O4
          aws configure set aws_secret_access_key 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
          aws configure set region Europe (Stockholm) eu-north-1

      - name: Sync files to S3 bucket
        run: |
          aws s3 sync . s3://21ita38
